### ISSUE TITLE
小程序里怎么使用？

### ISSUE THREAD

**Issue by WuJiY** [zhang-quan-yi/skus#1]
最近在做小程序商城，刚好用到sku查询的算法。

**Comment by zhang-quan-yi** [comment]
并没有做太多的封装，所以和平台不相关的。
只需要根据 `path.light` （表示规格是否可用），显示到页面上就行了。
关于用法，我更新了 `README` 文件。

**Comment by WuJiY** [comment]
使用alg_2_2.js 这个文件的算法吗

**Comment by zhang-quan-yi** [comment]
都可以用的，用法也都一样；
建议用第一种：alg_1.js，它对sku的顺序没有要求，比如：

```
let skus = [
    ['红色','中号','套餐1']
];

# 和
let skus = [
    ['套餐1','红色','中号']
];

# 这里的sku的顺序可以随意的；
# 而alg_2_1、alg_2_2算法要求 sku 的顺序保持一致，也就是说：

let maps = [
    颜色: ['颜色1',颜色2','颜色3'],
    尺寸: ['尺寸1','尺寸'],
    套餐: ['套餐1','套餐2','套餐3']
];

let skus = [
    [颜色,尺寸,套餐]  // 顺序需要和 maps 对应；
]

```

**Comment by WuJiY** [comment]
这几个算法都是一样的？只是初始数据格式不一样

**Comment by zhang-quan-yi** [comment]
用法是一样的；

不一样的是：
1. 初始化数据；
2. 内部机制不同；`alg_1` 与 `alg_2` 不同；`alg_2_2` 是 `alg_2_1` 的改进

**Comment by WuJiY** [comment]
好的，谢谢，我试试

**Comment by WuJiY** [comment]
有没有最终选择的sku 的方法？

**Comment by WuJiY** [comment]
选择还是有问题，现在只是单个选择ok的，但是组合选择就会出问题

**Comment by zhang-quan-yi** [comment]
`组合选择`是什么意思？

**Comment by WuJiY** [comment]
比如 颜色和尺寸两个属性这样结构
颜色：['红','黄','蓝']
尺寸：['170','180']
其中是没有蓝+180的sku的，所以我点击蓝，则180置为灰色。
但是问题来了，我在点击170的时候，此时180就变为可选状态了。。。因为每次path.add的时候都是一个属性判断

**Comment by WuJiY** [comment]
好吧，关于组合选择的问题我解决了，直接循环一下light 排除一下就好了，另外有没有最终选择的sku 的方法

**Comment by zhang-quan-yi** [comment]
做了两处修改：
1.增加了 `getSkuIndex` 方法：如果所有选项都选取了（即选取了最终的sku），会返回所选sku的下标；如果选项不完整，返回-1；
2. `add` 方法：返回值与 `getSkuIndex` 方法相同（可以看 `/test/index.js` 中的测试示例）

**Comment by WuJiY** [comment]
这个 this.selected = []; 好像有问题 每次选择 ，都是显示当前选中的。下面是两次选择
![image](https://user-images.githubusercontent.com/183884/49053449-1f73d300-f22b-11e8-87de-c3c3da5a6e0b.png)

![image](https://user-images.githubusercontent.com/183884/49053429-0ec35d00-f22b-11e8-97ca-ee016d3e509b.png)

**Comment by zhang-quan-yi** [comment]
完整一点的代码？

**Comment by WuJiY** [comment]
maps原始 结构
```
[
  {
    "id":1,
    "name":"口味",
    "sel":[65,68],
    "self":[65:{'vid':65,"name":"aaa"},68:{'vid':68,"name":"bbb"}]},
  {
    "id":2,
    "name":"颜色",
    "sel":[69,70],
    "self":[69:{'vid':69,"name":"111"},70:{'vid':70,"name":"222"}]},
]
```
 (传给path的时候我已经格式化成需要的格式) 
```
[
  [65,68],
  [69,70]
]
```
skus 结构 
```
[
 "65;69"：{"skuid":1,"barcode":"12345"},
 "68;69"：{"skuid":2,"barcode":"56789"},
 "65;70"：{"skuid":3,"barcode":"98765"},
]
```
(传给path的时候我已经格式化成需要的格式)
```
[
 [65, 68],
 [65, 70],
 [69, 68]
]
```

点击某一个属性获得属性的索引index1 值索引为index2 ，属性的id为 spvalueId
```
maps[index1].sel.map((v, k) => {
      if (v !== spvalueId) {
        if (maps[index1].self[v].checked) {
          path.del([index1, k]);
          maps[index1].self[v].checked = false;
        }
      } else {
        if (maps[index1].self[v].checked) {
          path.del([index1, k]);
          maps[index1].self[v].checked = false;
        } else {
          path.add([index1, k]);
          maps[index1].self[v].checked = true;
        }
      }
    });
```

然后根据light判断是否可以点击
```
path.light.forEach((v, k) => {
      if (k != index1) {
        v.forEach((v1, k1) => {
          if (s === 0) {
            maps[k].self[maps[k].sel[k1]].notallow = true;
          } else {
            maps[k].self[maps[k].sel[k1]].notallow = false;
          }
        });
      }
    });
```

**Comment by zhang-quan-yi** [comment]
![image](https://user-images.githubusercontent.com/12481444/49067307-aaba8c00-f25e-11e8-9123-1c330ae0301e.png)
如果这个是`sku`组合的化，`[65, 68]` 这一组有问题；

**Comment by zhang-quan-yi** [comment]
判断属性值是否可以点击：
```javascript
var canClick = function(index1,index2){
  return path.light[index1][index2]>0;
};
```

**Comment by WuJiY** [comment]
> ![image](https://user-images.githubusercontent.com/12481444/49067307-aaba8c00-f25e-11e8-9123-1c330ae0301e.png)
> 如果这个是`sku`组合的化，`[65, 68]` 这一组有问题；

这个笔误，写错了～～～

**Comment by WuJiY** [comment]
还有就是 maps 三层的话 是不是就无效了？

**Comment by zhang-quan-yi** [comment]
三层? 意思是 `maps` 是一个三维数组吗？有实际示例吗？

**Comment by WuJiY** [comment]
maps:
`[
    [65,69],
    [68],
    [71,72]
]`

skus:

`[
    [65,68,71],
    [65,68,72],
    [69,68,72]
]`

**Comment by zhang-quan-yi** [comment]
没限制的，测试数据就是三层的；

**Comment by WuJiY** [comment]
三层的时候 alg_2_2 这个出问题，alg_1这个正常

**Comment by zhang-quan-yi** [comment]
确实有问题，谢谢了；
